---

- include_tasks: package_install.yml
  when: not reset_cluster

- include_tasks: setup_helm.yml
  when: not reset_cluster

- include_tasks: validations.yml

- include_tasks: setup_kubernetes.yml

- include_tasks: setup_catalog.yml

- name: "Restrict permissions on docker socket (needed until 'meta: reset_connection' is supported)."
  file:
    path: /var/run/docker.sock
    mode: 0660
  become: true
  when: ec2_install
