---
  - name: create etcd-cert tmp directory
    file:
      path: /tmp/etcd-cert
      state: directory
    when: etcd_ca_cert is not defined and etcd_client_cert is not defined and etcd_client_key is not defined

  - name: Create self signing ca cert
    shell: 'openssl req -nodes -x509 -newkey rsa:4096 -keyout /tmp/etcd-cert/key.pem -out /tmp/etcd-cert/cert.pem -days 365 -subj "/CN=asb-etcd.ansible-service-broker.svc"'
    when: etcd_ca_cert is not defined and etcd_client_cert is not defined and etcd_client_key is not defined

  - name: Create self signed client cert
    shell: 'openssl genrsa -out /tmp/etcd-cert/MyClient1.key 2048 \
    && openssl req -new -key /tmp/etcd-cert/MyClient1.key -out /tmp/etcd-cert/MyClient1.csr -subj "/CN=client" \
    && openssl x509 -req -in /tmp/etcd-cert/MyClient1.csr -CA /tmp/etcd-cert/cert.pem -CAkey /tmp/etcd-cert/key.pem -CAcreateserial -out /tmp/etcd-cert/MyClient1.pem -days 1024'
    when: etcd_ca_cert is not defined and etcd_client_cert is not defined and etcd_client_key is not defined

  - block:
    - shell: cat /tmp/etcd-cert/cert.pem
      register: cat_etcd_ca_cert
    - set_fact:
        etcd_ca_cert: "{{ cat_etcd_ca_cert.stdout }}"
    when: etcd_ca_cert is not defined

  - block:
    - shell: cat /tmp/etcd-cert/MyClient1.pem
      register: cat_etcd_client_cert
    - set_fact:
        etcd_client_cert: "{{ cat_etcd_client_cert.stdout }}"
    when: etcd_client_cert is not defined

  - block:
    - shell: cat /tmp/etcd-cert/MyClient1.key
      register: cat_etcd_client_key
    - set_fact:
        etcd_client_key: "{{ cat_etcd_client_key.stdout }}"
    when: etcd_client_key is not defined

  - name: Add etcd authentication if values are defined to deployment command
    set_fact:
      cmd_process_asb_template: >-
        {{ cmd_process_asb_template }}
        -p ETCD_IMAGE={{ etcd_image }}
        -p ETCD_PATH={{ etcd_path }}
        -p ETCD_TRUSTED_CA_FILE=/var/run/etcd-auth-secret/ca.crt
        -p BROKER_CLIENT_CERT_PATH=/var/run/asb-etcd-auth/client.crt
        -p BROKER_CLIENT_KEY_PATH=/var/run/asb-etcd-auth/client.key
        -p ETCD_TRUSTED_CA='{{ etcd_ca_cert | b64encode }}'
        -p BROKER_CLIENT_CERT='{{ etcd_client_cert | b64encode }}'
        -p BROKER_CLIENT_KEY='{{ etcd_client_key | b64encode }}'
        -p NAMESPACE='{{ asb_project }}'
    when: etcd_ca_cert is defined and etcd_client_cert is defined and etcd_client_key is defined
