---

broker_registry_type: rhcc
broker_registry_url: http://registry.access.stage.redhat.com
broker_image_name: registry.access.stage.redhat.com/openshift3/ansible-service-broker
etcd_image_name: registry.access.redhat.com/rhel7/etcd
etcd_path: "/bin/etcd"
origin_image_name: registry.ops.openshift.com/openshift3/ose
origin_image_tag: v3.6
