template_dest: /tmp/k8s-ansible-service-broker.yaml

asb_registry: "ansibleplaybookbundle"
dockerhub_user_name: changeme
dockerhub_user_password: changeme

asb_src_dir: /tmp/ansible-service-broker

broker_tag: "latest"
broker_image_name: "{{ asb_registry }}/ansible-service-broker-apb"
broker_image: "{{ broker_image_name }}:{{ broker_tag }}"

etcd_tag: "latest"
etcd_image_name: "{{ asb_registry }}/ansible-service-broker-etcd"
etcd_image: "{{ etcd_image_name }}:{{ etcd_tag }}"


#
# Template defaults
#

# Path of the etcd binary
etcd_path: /usr/local/bin/etcd

# Configuration filepath for Ansible Service Broker
broker_config: /etc/ansible-service-broker/config.yaml

# APB Image Tag
tag: latest

# OpenShift info
openshift_pass: admin
openshift_user: admin
openshift_target: kubernetes.default

# Registry Info
registry_type: dockerhub
registry_name: dh
registry_url: https://registry.hub.docker.com

# Include Broker Development Endpoint
dev_broker: "true"

# Sandbox Permissions
sandbox_role: "edit"
auto_escalate: "true"
keep_namespace: "false"
keep_namespace_on_error: "true"

# Url Prefix
broker_url_prefix: "/ansible-service-broker"

# Launch APB on bind
launch_apb_on_bind: "false"

# Will automatically bootstrap the broker on startup
bootstrap_on_startup: "true"

# Refresh the available broker images every interval of seconds
refresh_interval: "600s"

# Output broker requests to log
output_request: "true"

# Recover unfinshed jobs on restart
recovery: "true"

# APB ImagePullPolicy
image_pull_policy: "IfNotPresent"

# Will enable basic authentication
enable_basic_auth: "false"

############################################################
# NOTE: These values MUST be base64 encoded.
# http://red.ht/2wbrCYo states "The value associated with
# keys in the data map must be base64 encoded."
############################################################
broker_pass: YWRtaW4=
broker_user: YWRtaW4=

############################################################
# NOTE: Default behavior for these are going to use the kubernetes
# InClusterConfig. These are typically overridden for running
# the broker outside of a cluster. Under normal circumstances,
# you probably want to leave these blank.
############################################################
ca_file: ""
bearer_token_file: ""
cluster_auth_host: ""

# playbook will use the value of 'broker_version' to index into this map
# normally broker_version is set from 'broker_tag' yet for custom images
# user may want to run an arbitray tag,
# then they must set broker_version correctly
ansible_broker_deployment_info:
  'v3.6':
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/release-0.9/templates/deploy-ansible-service-broker.template.yaml
  'v3.7':
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.0/templates/deploy-ansible-service-broker.template.yaml
  'v3.9':
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/release-1.1/templates/deploy-ansible-service-broker.template.yaml
  latest:
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
  nightly:
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
  canary:
    template_url: https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
